# Generated by Django 4.0.6 on 2022-09-27 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='email',
        ),
        migrations.RemoveField(
            model_name='form',
            name='password',
        ),
        migrations.RemoveField(
            model_name='form',
            name='username',
        ),
        migrations.AddField(
            model_name='form',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='created_date',
            field=models.DateTimeField(default=True),
        ),
        migrations.AddField(
            model_name='form',
            name='desription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
