# Generated by Django 4.0.6 on 2022-09-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_form_email_remove_form_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['completed']},
        ),
        migrations.AlterField(
            model_name='form',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
